apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerconnect-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerconnect-backend
  template:
    metadata:
      labels:
        app: commerconnect-backend
    spec:
      containers:
      - name: commerconnect-backend
        image: samhithraj/commerconnect-backend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: commerconnect-backend-service
spec:
  selector:
    app: commerconnect-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP