apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerconnect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerconnect-frontend
  template:
    metadata:
      labels:
        app: commerconnect-frontend
    spec:
      containers:
      - name: commerconnect-frontend
        image: samhithraj/commerconnect-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: commerconnect-frontend-service
spec:
  selector:
    app: commerconnect-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer